sudo: required

services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint

deploy:
  matrix:
    - provider: heroku
  api_key:
    secure: Lpck25BJc1V2WMzuzly5oPbXgo+K/V2DSX+NwFM3mYT4SYCQLkaly24KXHuQolA/kVg8YHsLatD/o6VowQxQ7Om0v58AkRKg2VCEChgko5pxSpjlrk0xVA+eu2KG0MvCbRYLIEucjNXNRYYJUE8PBoFrQbs0aTjiw/qHfXZSz0RTYrZu4vQwhEgbb0LDq0tKOtOzk1QubqJHkWpZrqcYwhUQl5hpGD6MobaV7qJ3LpwNt92PBAArZnGejP+ewpULm3lJ+u1Pb9m3bw+pA3rfDqMYgWx5KjVv7F9O9nWhJB2O32s11gT9q6Zj+LvVyrkVM8Hdms2JB40HJ1+UAIEzEkQFuL4Wc1zuUdH2InFoFrQr4q2OMdP8+U7JOm26bZUol9u24AbjlwFgNbhXGLSNTcrgxApWTmKSInnCjbw/v1X20o5LnkyPpzGAfHMYb2I1mEP+mR93+ty/qOh9p0NabybQCZlKlSD9eqE/Pp1BAfMkdopICPXFaLcb03ossxZ7FAjHOLumfA4y7cFxorIQfH9FLUFkb4w40hNQpSHA6bu91JIaZi6f7Svl/L2iiyuh2iL+O7RKJIhY5x3+gSSYSjmjAdoW5ACCwiMOaIN6qXpxwKGTfETLJaww7Kgp9GZ2Q5Triw6JXx8DES1pIgePM0muK4/3iifI8uzJkZvBlVM=
  on: heroku_production
  app: probot-coursera

  
